# Generated by Django 4.0.3 on 2022-03-11 08:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_project_project_comments_project_project_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_team',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
