# Generated by Django 4.0.3 on 2022-03-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_project_project_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_progress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
